//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applied
    {
        public long AppliedId { get; set; }
        public string AddvertiseNo { get; set; }
        public string CandidateName { get; set; }
        public string FatherName { get; set; }
        public string CNIC { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> JobType { get; set; }
        public string JobTitle { get; set; }
        public Nullable<long> DesignationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<long> ShiftId { get; set; }
        public Nullable<decimal> MinExpereince { get; set; }
        public Nullable<decimal> MaxExpereince { get; set; }
        public string MInQualification { get; set; }
        public string Location { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string Skills { get; set; }
        public string AppliedFrom { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public Nullable<decimal> ExpectedSalary { get; set; }
        public Nullable<int> Currency { get; set; }
        public string Photo { get; set; }
        public string Status { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
