//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public long AttendaceId { get; set; }
        public long EmployeeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public Nullable<bool> IsAbsent { get; set; }
        public Nullable<bool> IsLeave { get; set; }
        public Nullable<long> LeaveType { get; set; }
        public Nullable<bool> IsHoliDay { get; set; }
        public Nullable<long> HoliDay { get; set; }
        public Nullable<bool> IsHalfDay { get; set; }
        public Nullable<bool> IsLate { get; set; }
        public Nullable<bool> IsEarly { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    }
}
