//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTransfer
    {
        public long TransferId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<long> DesignationId { get; set; }
        public Nullable<long> NewDesignationId { get; set; }
        public Nullable<long> FromDepartmentId { get; set; }
        public Nullable<long> ToDepartmentId { get; set; }
        public string TrasnferReason { get; set; }
        public Nullable<System.DateTime> TrasnferDate { get; set; }
        public Nullable<long> TrasnferedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
