//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrmEmployeeEducation
    {
        public long EducationId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<int> QualificationType { get; set; }
        public string Degree { get; set; }
        public string Subject { get; set; }
        public string Grade { get; set; }
        public string Division { get; set; }
        public string GPA { get; set; }
        public string TotalGPA { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string PassingYear { get; set; }
        public string Institutes { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
