//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrmEmployeementHistory
    {
        public long EmpExpId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<int> JobType { get; set; }
        public string Organization { get; set; }
        public string OrganizationAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ReasonForLeaaving { get; set; }
        public Nullable<decimal> LastSalary { get; set; }
        public string Currency { get; set; }
        public string JobDescription { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
