//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrmInternalRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HrmInternalRequisition()
        {
            this.HrmJobPosts = new HashSet<HrmJobPost>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string RequisitionNumber { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> HrmGradeId { get; set; }
        public Nullable<int> ContractDuration { get; set; }
        public Nullable<int> RequestedBy { get; set; }
        public string PositionStatus { get; set; }
        public string Description { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> ReplacePositionId { get; set; }
        public Nullable<int> RepalceToId { get; set; }
        public Nullable<int> RepalceToGradeId { get; set; }
        public Nullable<int> NoOfPositions { get; set; }
        public Nullable<int> Qualification { get; set; }
        public Nullable<int> MinExperience { get; set; }
        public Nullable<bool> ShiftRotation { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Designation Designation1 { get; set; }
        public virtual HrmEmployee HrmEmployee { get; set; }
        public virtual HrmEmployee HrmEmployee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrmJobPost> HrmJobPosts { get; set; }
    }
}
