//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrmInterviewDetail
    {
        public int Id { get; set; }
        public Nullable<int> HrmInterviewId { get; set; }
        public Nullable<int> HrmEmployeeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Venue { get; set; }
        public string Description { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> EarnedScore { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual HrmEmployee HrmEmployee { get; set; }
        public virtual HrmInterview HrmInterview { get; set; }
    }
}
