//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrmJobPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HrmJobPost()
        {
            this.HrmInterviews = new HashSet<HrmInterview>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HrmInternalRequisitionId { get; set; }
        public string JobPostCode { get; set; }
        public string JobTitle { get; set; }
        public string HrmJobType { get; set; }
        public Nullable<decimal> DurationMonths { get; set; }
        public Nullable<int> HrmShiftId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> Req { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SubDepartmentId { get; set; }
        public Nullable<int> TotalPosition { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<double> ExperienceYears { get; set; }
        public Nullable<double> MinSalaryRange { get; set; }
        public Nullable<double> MaxSalaryRange { get; set; }
        public Nullable<int> Qualification { get; set; }
        public string JoDescription { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> EndedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> HrmJobType_Id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual HrmEmployee HrmEmployee { get; set; }
        public virtual HrmInternalRequisition HrmInternalRequisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrmInterview> HrmInterviews { get; set; }
        public virtual HrmJobType HrmJobType1 { get; set; }
    }
}
