//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewAssessment
    {
        public int PK_InterviewId { get; set; }
        public Nullable<long> AppliedId { get; set; }
        public string Education { get; set; }
        public string ComputerLiteracy { get; set; }
        public string Intelligence { get; set; }
        public string ExperienceInterviewed { get; set; }
        public string ExperienceCompanyBusiness { get; set; }
        public string JobKnowledgeSkill { get; set; }
        public string Personality { get; set; }
        public string CommunicationSkills { get; set; }
        public string DevelopmentMotivation { get; set; }
        public string PersonalAptitude { get; set; }
        public string Comments { get; set; }
    }
}
