//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> JobType { get; set; }
        public string ShiftId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<decimal> MinExpereince { get; set; }
        public Nullable<decimal> MaxExpereince { get; set; }
        public string MInQualification { get; set; }
        public Nullable<int> NoOfposition { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string Location { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Skills { get; set; }
        public string SalaryRange { get; set; }
        public string jobDescription { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
