//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerKeyResult
    {
        public long Id { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<long> GrossSalary { get; set; }
        public Nullable<bool> FitForPromotion { get; set; }
        public Nullable<bool> FitInCurrentPossition { get; set; }
        public Nullable<bool> NotFitForPromotionButLikelyToBecome { get; set; }
        public Nullable<bool> UnfitForPromotionHasReachedHisCeiling { get; set; }
        public Nullable<bool> EligibleForBonus { get; set; }
        public Nullable<int> EligibleForIncrementPercentage { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
