//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMSEntities : DbContext
    {
        public HRMSEntities()
            : base("name=HRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvanceSalary> AdvanceSalarys { get; set; }
        public virtual DbSet<Applied> Applieds { get; set; }
        public virtual DbSet<ApplyCandidate> ApplyCandidates { get; set; }
        public virtual DbSet<Arrear> Arrears { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<BonusSetup> BonusSetups { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CostingTab> CostingTabs { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Deduction> Deductions { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<EmployeeCost> EmployeeCosts { get; set; }
        public virtual DbSet<EmployeeGroup> EmployeeGroups { get; set; }
        public virtual DbSet<EmployeeTransfer> EmployeeTransfers { get; set; }
        public virtual DbSet<EmployeeVisaDetail> EmployeeVisaDetails { get; set; }
        public virtual DbSet<HrmEmployeeEducation> HrmEmployeeEducations { get; set; }
        public virtual DbSet<HrmEmployeeHealth> HrmEmployeeHealths { get; set; }
        public virtual DbSet<HrmEmployeementHistory> HrmEmployeementHistories { get; set; }
        public virtual DbSet<HrmEmployeeRefrence> HrmEmployeeRefrences { get; set; }
        public virtual DbSet<HrmEmployeeRelation> HrmEmployeeRelations { get; set; }
        public virtual DbSet<HrmEmployee> HrmEmployees { get; set; }
        public virtual DbSet<HrmInternalRequisition> HrmInternalRequisitions { get; set; }
        public virtual DbSet<HrmInterviewDetail> HrmInterviewDetails { get; set; }
        public virtual DbSet<HrmInterview> HrmInterviews { get; set; }
        public virtual DbSet<HrmJobPost> HrmJobPosts { get; set; }
        public virtual DbSet<HrmJobType> HrmJobTypes { get; set; }
        public virtual DbSet<HrmSkill> HrmSkills { get; set; }
        public virtual DbSet<InterviewAssessment> InterviewAssessments { get; set; }
        public virtual DbSet<JobRequisition> JobRequisitions { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<KeyObjective> KeyObjectives { get; set; }
        public virtual DbSet<KeyResult> KeyResults { get; set; }
        public virtual DbSet<LeavePolicy> LeavePolicies { get; set; }
        public virtual DbSet<LeaveRequest> LeaveRequests { get; set; }
        public virtual DbSet<LoanSanction> LoanSanctions { get; set; }
        public virtual DbSet<LoanType> LoanTypes { get; set; }
        public virtual DbSet<OfferLetter> OfferLetters { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OverTimeSetup> OverTimeSetups { get; set; }
        public virtual DbSet<PayRollCutOff> PayRollCutOffs { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<SalarySetup> SalarySetups { get; set; }
        public virtual DbSet<ShiftMaster> ShiftMasters { get; set; }
        public virtual DbSet<SpecialAllowance> SpecialAllowances { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Termination> Terminations { get; set; }
        public virtual DbSet<TradeLicens> TradeLicenses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Allowance> Allowances { get; set; }
        public virtual DbSet<AllowancesDeduction> AllowancesDeductions { get; set; }
        public virtual DbSet<AllowanceType> AllowanceTypes { get; set; }
        public virtual DbSet<HrmAttendance> HrmAttendances { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<PublicHoliday> PublicHolidays { get; set; }
        public virtual DbSet<tbl_EmployeeAttendanceCalculations> tbl_EmployeeAttendanceCalculations { get; set; }
    }
}
