//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferLetter
    {
        public int PK_OfferLetterId { get; set; }
        public string EmployeeId { get; set; }
        public string DesignationId { get; set; }
        public string DepartmentId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Salary { get; set; }
    }
}
