//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryCalculationDetail
    {
        public long Id { get; set; }
        public Nullable<long> SalaryHdrId { get; set; }
        public Nullable<int> AllowanceId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public Nullable<decimal> BonusSetup { get; set; }
        public Nullable<decimal> LoanInstallment { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual SalaryCalculationHeader SalaryCalculationHeader { get; set; }
    }
}
