//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryCalculationHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalaryCalculationHeader()
        {
            this.SalaryCalculationDetails = new HashSet<SalaryCalculationDetail>();
        }
    
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public string SalaryMonth { get; set; }
        public Nullable<System.DateTime> SalaryDate { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<int> OThours { get; set; }
        public Nullable<decimal> OTAmount { get; set; }
        public Nullable<decimal> TotalSalaryAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryCalculationDetail> SalaryCalculationDetails { get; set; }
    }
}
