//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftMaster
    {
        public long ShiftId { get; set; }
        public string ShiftName { get; set; }
        public string Code { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> GressTime { get; set; }
        public Nullable<System.TimeSpan> EarlyLeave { get; set; }
        public Nullable<System.TimeSpan> HalfDay { get; set; }
        public Nullable<bool> IsFridayOff { get; set; }
        public Nullable<bool> IsSaturdayOff { get; set; }
        public Nullable<bool> IsSundayOff { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    }
}
