//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeeAttendanceCalculations
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public Nullable<int> PresentDays { get; set; }
        public Nullable<int> LeaveDays { get; set; }
        public Nullable<int> AbsentDays { get; set; }
        public string TotalHoursWorked { get; set; }
        public Nullable<int> NormalOTHours { get; set; }
        public Nullable<int> WeekendOTHours { get; set; }
        public Nullable<int> PublicHolidaysOTHours { get; set; }
    }
}
