//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termination
    {
        public long TerminatinId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<long> DesignationId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<long> ToDepartmentId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> LastWorkingDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> TerminationBy { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
