'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ApplyCandidate
    Public Property AppliedId As Long
    Public Property JobId As Nullable(Of Long)
    Public Property CandidateName As String
    Public Property FatherName As String
    Public Property CNIC As String
    Public Property ContactNumber As String
    Public Property Email As String
    Public Property AppliedFrom As String
    Public Property ApplyDate As Nullable(Of Date)
    Public Property AvailableDate As Nullable(Of Date)
    Public Property Photo As String
    Public Property Attachment As String
    Public Property Status As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
