'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Attendance
    Public Property AttendaceId As Long
    Public Property EmployeeId As Long
    Public Property [Date] As Nullable(Of Date)
    Public Property TimeIn As Nullable(Of System.TimeSpan)
    Public Property TimeOut As Nullable(Of System.TimeSpan)
    Public Property IsPresent As Nullable(Of Boolean)
    Public Property IsAbsent As Nullable(Of Boolean)
    Public Property IsLeave As Nullable(Of Boolean)
    Public Property LeaveType As Nullable(Of Long)
    Public Property IsHoliDay As Nullable(Of Boolean)
    Public Property HoliDay As Nullable(Of Long)
    Public Property IsHalfDay As Nullable(Of Boolean)
    Public Property IsLate As Nullable(Of Boolean)
    Public Property IsEarly As Nullable(Of Boolean)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property UpdatedOn As Nullable(Of Date)
    Public Property UpdatedBy As Nullable(Of Long)

End Class
