'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmployeeTransfer
    Public Property TransferId As Long
    Public Property EmployeeId As Nullable(Of Long)
    Public Property DesignationId As Nullable(Of Long)
    Public Property NewDesignationId As Nullable(Of Long)
    Public Property FromDepartmentId As Nullable(Of Long)
    Public Property ToDepartmentId As Nullable(Of Long)
    Public Property TrasnferReason As String
    Public Property TrasnferDate As Nullable(Of Date)
    Public Property TrasnferedBy As Nullable(Of Long)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
