'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HrmEmployeeHealth
    Public Property EmpHealthId As Long
    Public Property EmployeeId As Nullable(Of Long)
    Public Property DiseasName As String
    Public Property Result As String
    Public Property FromSuffering As String
    Public Property Treatment As String
    Public Property Attachment As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property UpdatedBy As Nullable(Of Long)
    Public Property UpdatedOn As Nullable(Of Date)

End Class
