'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HrmEmployee
    Public Property Id As Integer
    Public Property TitleId As Nullable(Of Integer)
    Public Property FirstName As String
    Public Property Middlename As String
    Public Property LastName As String
    Public Property EmployeeCode As String
    Public Property Gender As String
    Public Property FatherHusbandName As String
    Public Property DateOfBirth As Nullable(Of Date)
    Public Property IdentityCardNo As String
    Public Property IdentityExpiryDate As Nullable(Of Date)
    Public Property ReligionId As Nullable(Of Integer)
    Public Property MaritalStatus As String
    Public Property Dependants As Nullable(Of Integer)
    Public Property NationalCountryId As Nullable(Of Integer)
    Public Property EthnicityId As Nullable(Of Integer)
    Public Property BloodGroup As String
    Public Property HrmLanguageId As Nullable(Of Integer)
    Public Property DisabilitiesId As Nullable(Of Integer)
    Public Property EmployeeType As String
    Public Property EmployeeGroupId As Nullable(Of Integer)
    Public Property HrmLocationOficeId As Nullable(Of Integer)
    Public Property DesignationId As Nullable(Of Integer)
    Public Property ReportToId As Nullable(Of Integer)
    Public Property DepartmentId As Nullable(Of Integer)
    Public Property SubDepartmentId As Nullable(Of Integer)
    Public Property HrmGradeId As Nullable(Of Integer)
    Public Property MachineId As String
    Public Property JoiningDate As Nullable(Of Date)
    Public Property ProbationPeriod As Nullable(Of Integer)
    Public Property ConfirmationDate As Nullable(Of Date)
    Public Property ContractExpiryDate As Nullable(Of Date)
    Public Property BasicSalary As Nullable(Of Double)
    Public Property ContacNo As String
    Public Property Email As String
    Public Property LivingCountryId As Nullable(Of Integer)
    Public Property StateId As Nullable(Of Integer)
    Public Property CityId As Nullable(Of Integer)
    Public Property ZipCode As String
    Public Property CurrentAddress As String
    Public Property CurrentCountryId As Nullable(Of Integer)
    Public Property CurrentStateId As Nullable(Of Integer)
    Public Property CurrentCityId As Nullable(Of Integer)
    Public Property CurrentZipCode As String
    Public Property UserName As String
    Public Property Password As String
    Public Property IswebloginAllowed As Nullable(Of Boolean)
    Public Property SoftRoleinformation As String
    Public Property ApplicationUserId As String
    Public Property ProfilePicture As String
    Public Property CostCenterId As Nullable(Of Integer)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)
    Public Property Country_Id As Nullable(Of Integer)
    Public Property BiometricCode As String
    Public Property Title As String
    Public Property Passport As String
    Public Property DrivingLicence As String
    Public Property BirthCountryId As Nullable(Of Integer)
    Public Property HrmLanguage As String
    Public Property ProbationType As String
    Public Property OfficialNo As String
    Public Property OfficialEmail As String
    Public Property RegionId As Nullable(Of Integer)
    Public Property PermnantAddress As String
    Public Property BankName As String
    Public Property BranchCode As String
    Public Property BranchName As String
    Public Property AccountTitle As String
    Public Property AccountNumber As String
    Public Property AccountType As String
    Public Property PassportExpiryDate As Nullable(Of Date)
    Public Property ShiftId As Nullable(Of Long)

    Public Overridable Property AspNetRole As AspNetRole
    Public Overridable Property AspNetUser As AspNetUser
    Public Overridable Property City As City
    Public Overridable Property City1 As City
    Public Overridable Property Country As Country
    Public Overridable Property Country1 As Country
    Public Overridable Property Country2 As Country
    Public Overridable Property Country3 As Country
    Public Overridable Property Departments As ICollection(Of Department) = New HashSet(Of Department)
    Public Overridable Property Department As Department
    Public Overridable Property Department1 As Department
    Public Overridable Property Designation As Designation
    Public Overridable Property HrmEmployees1 As ICollection(Of HrmEmployee) = New HashSet(Of HrmEmployee)
    Public Overridable Property HrmEmployee1 As HrmEmployee
    Public Overridable Property HrmInternalRequisitions As ICollection(Of HrmInternalRequisition) = New HashSet(Of HrmInternalRequisition)
    Public Overridable Property HrmInternalRequisitions1 As ICollection(Of HrmInternalRequisition) = New HashSet(Of HrmInternalRequisition)
    Public Overridable Property HrmInterviewDetails As ICollection(Of HrmInterviewDetail) = New HashSet(Of HrmInterviewDetail)
    Public Overridable Property HrmInterviews As ICollection(Of HrmInterview) = New HashSet(Of HrmInterview)
    Public Overridable Property HrmJobPosts As ICollection(Of HrmJobPost) = New HashSet(Of HrmJobPost)
    Public Overridable Property KeyResults As ICollection(Of KeyResult) = New HashSet(Of KeyResult)

End Class
