'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Job
    Public Property JobId As Integer
    Public Property JobTitle As String
    Public Property JobType As Nullable(Of Integer)
    Public Property ShiftId As String
    Public Property DepartmentId As Nullable(Of Integer)
    Public Property DesignationId As Nullable(Of Integer)
    Public Property MinExpereince As Nullable(Of Decimal)
    Public Property MaxExpereince As Nullable(Of Decimal)
    Public Property MInQualification As String
    Public Property NoOfposition As Nullable(Of Integer)
    Public Property ClosingDate As Nullable(Of Date)
    Public Property Location As String
    Public Property Gender As String
    Public Property Age As Nullable(Of Integer)
    Public Property Skills As String
    Public Property SalaryRange As String
    Public Property jobDescription As String
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
