'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class JobRequisition
    Public Property ReqId As Long
    Public Property AddvertiseNo As String
    Public Property JobType As Nullable(Of Integer)
    Public Property JobTitle As String
    Public Property DesignationId As Nullable(Of Long)
    Public Property DepartmentId As Nullable(Of Long)
    Public Property ShiftId As Nullable(Of Long)
    Public Property MinExpereince As Nullable(Of Decimal)
    Public Property MaxExpereince As Nullable(Of Decimal)
    Public Property MInQualification As String
    Public Property Location As String
    Public Property Gender As String
    Public Property Age As Nullable(Of Decimal)
    Public Property Skills As String
    Public Property LastDate As Nullable(Of Date)
    Public Property ExpectedSalary As Nullable(Of Decimal)
    Public Property Currency As String
    Public Property Status As Nullable(Of Integer)
    Public Property Attachment As String
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
