'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KeyObjective
    Public Property Id As Long
    Public Property DefineObjective As String
    Public Property DepId As Nullable(Of Long)
    Public Property AssignedTo As Nullable(Of Long)
    Public Property AssignDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property Priority As String
    Public Property Status As String
    Public Property AssignedPercentage As Nullable(Of Integer)
    Public Property CompletedPercentage As Nullable(Of Integer)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As Nullable(Of Long)
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property Deleted As Nullable(Of Boolean)

    Public Overridable Property KeyObjectives1 As KeyObjective
    Public Overridable Property KeyObjective1 As KeyObjective
    Public Overridable Property KeyResults As ICollection(Of KeyResult) = New HashSet(Of KeyResult)

End Class
