'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShiftMaster
    Public Property ShiftId As Long
    Public Property ShiftName As String
    Public Property Code As String
    Public Property StartTime As Nullable(Of System.TimeSpan)
    Public Property EndTime As Nullable(Of System.TimeSpan)
    Public Property GressTime As Nullable(Of System.TimeSpan)
    Public Property EarlyLeave As Nullable(Of System.TimeSpan)
    Public Property HalfDay As Nullable(Of System.TimeSpan)
    Public Property IsFridayOff As Nullable(Of Boolean)
    Public Property IsSaturdayOff As Nullable(Of Boolean)
    Public Property IsSundayOff As Nullable(Of Boolean)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property UpdatedOn As Nullable(Of Date)
    Public Property UpdatedBy As Nullable(Of Long)

End Class
