'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SpecialAllowance
    Public Property Id As Long
    Public Property EmployeeId As Nullable(Of Long)
    Public Property AllowanceType As Long
    Public Property Amount As Nullable(Of Decimal)
    Public Property PayRollMonth As String
    Public Property Effect As String
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As Nullable(Of Long)
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property Deleted As Nullable(Of Boolean)

End Class
