'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AllowancesDeduction
    Public Property Id As Integer
    Public Property Code As String
    Public Property FK_AllowanceId As Nullable(Of Long)
    Public Property Percentage As Nullable(Of Decimal)
    Public Property Amount As Nullable(Of Decimal)
    Public Property GLCode As Nullable(Of Integer)
    Public Property Effect As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
