'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetUser
    Public Property Id As String
    Public Property CreatedBy As String
    Public Property CreatedOn As Date
    Public Property IsDeleted As Boolean
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Date
    Public Property FirstName As String
    Public Property LastName As String
    Public Property PasswordToken As String
    Public Property DateOfJoining As Nullable(Of Date)
    Public Property AccountRole As String
    Public Property DateOfBirth As Nullable(Of Date)
    Public Property CellNumber As String
    Public Property Status As Integer
    Public Property Picture As String
    Public Property Email As String
    Public Property EmailConfirmed As Boolean
    Public Property PasswordHash As String
    Public Property SecurityStamp As String
    Public Property PhoneNumber As String
    Public Property PhoneNumberConfirmed As Boolean
    Public Property TwoFactorEnabled As Boolean
    Public Property LockoutEndDateUtc As Nullable(Of Date)
    Public Property LockoutEnabled As Boolean
    Public Property AccessFailedCount As Integer
    Public Property UserName As String

    Public Overridable Property AspNetUserLogins As ICollection(Of AspNetUserLogin) = New HashSet(Of AspNetUserLogin)
    Public Overridable Property AspNetUserRoles As ICollection(Of AspNetUserRole) = New HashSet(Of AspNetUserRole)
    Public Overridable Property HrmEmployees As ICollection(Of HrmEmployee) = New HashSet(Of HrmEmployee)

End Class
