'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Department
    Public Property Id As Integer
    Public Property CompanyId As Nullable(Of Integer)
    Public Property ParentDepartmentId As Nullable(Of Integer)
    Public Property DepartmentCode As String
    Public Property Name As String
    Public Property HrmDepartmentHeadId As Nullable(Of Integer)
    Public Property ReferenceId As Nullable(Of Integer)
    Public Property Active As Nullable(Of Boolean)
    Public Property IsSubDepartment As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

    Public Overridable Property Departments1 As ICollection(Of Department) = New HashSet(Of Department)
    Public Overridable Property Department1 As Department
    Public Overridable Property HrmEmployee As HrmEmployee
    Public Overridable Property HrmEmployees As ICollection(Of HrmEmployee) = New HashSet(Of HrmEmployee)
    Public Overridable Property HrmEmployees1 As ICollection(Of HrmEmployee) = New HashSet(Of HrmEmployee)
    Public Overridable Property HrmInternalRequisitions As ICollection(Of HrmInternalRequisition) = New HashSet(Of HrmInternalRequisition)
    Public Overridable Property HrmInternalRequisitions1 As ICollection(Of HrmInternalRequisition) = New HashSet(Of HrmInternalRequisition)
    Public Overridable Property HrmJobPosts As ICollection(Of HrmJobPost) = New HashSet(Of HrmJobPost)
    Public Overridable Property HrmJobPosts1 As ICollection(Of HrmJobPost) = New HashSet(Of HrmJobPost)
    Public Overridable Property HrmJobPosts2 As ICollection(Of HrmJobPost) = New HashSet(Of HrmJobPost)

End Class
