'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Designation
    Public Property Id As Integer
    Public Property CompanyId As Nullable(Of Integer)
    Public Property Name As String
    Public Property DesignationCode As String
    Public Property ReferenceId As Nullable(Of Integer)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

    Public Overridable Property HrmEmployees As ICollection(Of HrmEmployee) = New HashSet(Of HrmEmployee)
    Public Overridable Property HrmInternalRequisitions As ICollection(Of HrmInternalRequisition) = New HashSet(Of HrmInternalRequisition)
    Public Overridable Property HrmInternalRequisitions1 As ICollection(Of HrmInternalRequisition) = New HashSet(Of HrmInternalRequisition)
    Public Overridable Property HrmJobPosts As ICollection(Of HrmJobPost) = New HashSet(Of HrmJobPost)

End Class
