'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmployeeVisaDetail
    Public Property Id As Long
    Public Property VisaTitle As String
    Public Property VisaNumber As Nullable(Of Long)
    Public Property VisaIssuanceDate As Nullable(Of Date)
    Public Property VisaExpiryDate As Nullable(Of Date)
    Public Property LabourCardNumber As Nullable(Of Long)
    Public Property LabourCardCode As String
    Public Property LabourCardExpiry As Nullable(Of Date)
    Public Property InsuranceCardNumber As Nullable(Of Long)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As Nullable(Of Long)
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
