'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HrmEmployeeRelation
    Public Property RelationId As Long
    Public Property EmployeeId As Nullable(Of Long)
    Public Property RelationType As Nullable(Of Integer)
    Public Property FullName As String
    Public Property ContactNumber As String
    Public Property Email As String
    Public Property Address As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property UpdatedBy As Nullable(Of Long)
    Public Property UpdatedOn As Nullable(Of Date)

End Class
