'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HrmEmployeeEducation
    Public Property EducationId As Long
    Public Property EmployeeId As Nullable(Of Long)
    Public Property QualificationType As Nullable(Of Integer)
    Public Property Degree As String
    Public Property Subject As String
    Public Property Grade As String
    Public Property Division As String
    Public Property GPA As String
    Public Property TotalGPA As String
    Public Property Percentage As Nullable(Of Decimal)
    Public Property PassingYear As String
    Public Property Institutes As String
    Public Property Attachment As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property UpdatedBy As Nullable(Of Long)
    Public Property UpdatedOn As Nullable(Of Date)

End Class
