'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HrmEmployeementHistory
    Public Property EmpExpId As Long
    Public Property EmployeeId As Nullable(Of Long)
    Public Property JobType As Nullable(Of Integer)
    Public Property Organization As String
    Public Property OrganizationAddress As String
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property ReasonForLeaaving As String
    Public Property LastSalary As Nullable(Of Decimal)
    Public Property Currency As String
    Public Property JobDescription As String
    Public Property Attachment As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property UpdatedBy As Nullable(Of Long)
    Public Property UpdatedOn As Nullable(Of Date)

End Class
