'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HrmInternalRequisition
    Public Property Id As Integer
    Public Property CompanyId As Nullable(Of Integer)
    Public Property RequisitionNumber As String
    Public Property DepartmentId As Nullable(Of Integer)
    Public Property SubDepartmentId As Nullable(Of Integer)
    Public Property DesignationId As Nullable(Of Integer)
    Public Property HrmGradeId As Nullable(Of Integer)
    Public Property ContractDuration As Nullable(Of Integer)
    Public Property RequestedBy As Nullable(Of Integer)
    Public Property PositionStatus As String
    Public Property Description As String
    Public Property Amount As Nullable(Of Double)
    Public Property ReplacePositionId As Nullable(Of Integer)
    Public Property RepalceToId As Nullable(Of Integer)
    Public Property RepalceToGradeId As Nullable(Of Integer)
    Public Property NoOfPositions As Nullable(Of Integer)
    Public Property Qualification As Nullable(Of Integer)
    Public Property MinExperience As Nullable(Of Integer)
    Public Property ShiftRotation As Nullable(Of Boolean)
    Public Property Status As String
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

    Public Overridable Property Department As Department
    Public Overridable Property Department1 As Department
    Public Overridable Property Designation As Designation
    Public Overridable Property Designation1 As Designation
    Public Overridable Property HrmEmployee As HrmEmployee
    Public Overridable Property HrmEmployee1 As HrmEmployee
    Public Overridable Property HrmJobPosts As ICollection(Of HrmJobPost) = New HashSet(Of HrmJobPost)

End Class
