'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HrmInterviewDetail
    Public Property Id As Integer
    Public Property HrmInterviewId As Nullable(Of Integer)
    Public Property HrmEmployeeId As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property Time As Nullable(Of System.TimeSpan)
    Public Property Venue As String
    Public Property Description As String
    Public Property Score As Nullable(Of Integer)
    Public Property EarnedScore As Nullable(Of Integer)
    Public Property Remarks As String
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

    Public Overridable Property HrmEmployee As HrmEmployee
    Public Overridable Property HrmInterview As HrmInterview

End Class
