'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HrmJobPost
    Public Property Id As Integer
    Public Property HrmInternalRequisitionId As Nullable(Of Integer)
    Public Property JobPostCode As String
    Public Property JobTitle As String
    Public Property HrmJobType As String
    Public Property DurationMonths As Nullable(Of Decimal)
    Public Property HrmShiftId As Nullable(Of Integer)
    Public Property DesignationId As Nullable(Of Integer)
    Public Property Req As Nullable(Of Integer)
    Public Property DepartmentId As Nullable(Of Integer)
    Public Property SubDepartmentId As Nullable(Of Integer)
    Public Property TotalPosition As Nullable(Of Integer)
    Public Property ClosingDate As Nullable(Of Date)
    Public Property Gender As String
    Public Property Age As Nullable(Of Integer)
    Public Property ExperienceYears As Nullable(Of Double)
    Public Property MinSalaryRange As Nullable(Of Double)
    Public Property MaxSalaryRange As Nullable(Of Double)
    Public Property Qualification As Nullable(Of Integer)
    Public Property JoDescription As String
    Public Property Status As String
    Public Property Active As Nullable(Of Boolean)
    Public Property EndedOn As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)
    Public Property Department_Id As Nullable(Of Integer)
    Public Property HrmJobType_Id As Nullable(Of Integer)

    Public Overridable Property Department As Department
    Public Overridable Property Department1 As Department
    Public Overridable Property Department2 As Department
    Public Overridable Property Designation As Designation
    Public Overridable Property HrmEmployee As HrmEmployee
    Public Overridable Property HrmInternalRequisition As HrmInternalRequisition
    Public Overridable Property HrmInterviews As ICollection(Of HrmInterview) = New HashSet(Of HrmInterview)
    Public Overridable Property HrmJobType1 As HrmJobType

End Class
