'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InterviewAssessment
    Public Property PK_InterviewId As Integer
    Public Property AppliedId As Nullable(Of Long)
    Public Property Education As String
    Public Property ComputerLiteracy As String
    Public Property Intelligence As String
    Public Property ExperienceInterviewed As String
    Public Property ExperienceCompanyBusiness As String
    Public Property JobKnowledgeSkill As String
    Public Property Personality As String
    Public Property CommunicationSkills As String
    Public Property DevelopmentMotivation As String
    Public Property PersonalAptitude As String
    Public Property Comments As String

End Class
