'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KeyResult
    Public Property Id As Long
    Public Property DefineKeyResult As String
    Public Property KeyObjectiveId As Nullable(Of Long)
    Public Property AssignedTo As Nullable(Of Integer)
    Public Property AssignDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property Priority As String
    Public Property Status As String
    Public Property AssignedPercentage As Nullable(Of Integer)
    Public Property CompletedPercentage As Nullable(Of Integer)
    Public Property Remarks As String
    Public Property CompletionDate As Nullable(Of Date)
    Public Property PendingDays As Nullable(Of Long)
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As Nullable(Of Long)
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property Deleted As Nullable(Of Boolean)

    Public Overridable Property HrmEmployee As HrmEmployee
    Public Overridable Property KeyObjective As KeyObjective

End Class
