'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LeaveRequest
    Public Property Pk_LeaveRequest As Integer
    Public Property Employee As Nullable(Of Long)
    Public Property LeaveTypeId As Nullable(Of Long)
    Public Property DateFrom As Nullable(Of Date)
    Public Property DateTo As Nullable(Of Date)
    Public Property LeaveDays As Nullable(Of Integer)
    Public Property Reason As String
    Public Property IsActive As Nullable(Of Boolean)
    Public Property Status As String
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
