'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class HRMSEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=HRMSEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AdvanceSalarys() As DbSet(Of AdvanceSalary)
    Public Overridable Property Applieds() As DbSet(Of Applied)
    Public Overridable Property ApplyCandidates() As DbSet(Of ApplyCandidate)
    Public Overridable Property Arrears() As DbSet(Of Arrear)
    Public Overridable Property AspNetRoles() As DbSet(Of AspNetRole)
    Public Overridable Property AspNetUserLogins() As DbSet(Of AspNetUserLogin)
    Public Overridable Property AspNetUserRoles() As DbSet(Of AspNetUserRole)
    Public Overridable Property AspNetUsers() As DbSet(Of AspNetUser)
    Public Overridable Property Attendances() As DbSet(Of Attendance)
    Public Overridable Property BonusSetups() As DbSet(Of BonusSetup)
    Public Overridable Property Cities() As DbSet(Of City)
    Public Overridable Property CostingTabs() As DbSet(Of CostingTab)
    Public Overridable Property Countries() As DbSet(Of Country)
    Public Overridable Property Deductions() As DbSet(Of Deduction)
    Public Overridable Property Departments() As DbSet(Of Department)
    Public Overridable Property Designations() As DbSet(Of Designation)
    Public Overridable Property EmployeeCosts() As DbSet(Of EmployeeCost)
    Public Overridable Property EmployeeGroups() As DbSet(Of EmployeeGroup)
    Public Overridable Property EmployeeTransfers() As DbSet(Of EmployeeTransfer)
    Public Overridable Property EmployeeVisaDetails() As DbSet(Of EmployeeVisaDetail)
    Public Overridable Property HrmEmployeeEducations() As DbSet(Of HrmEmployeeEducation)
    Public Overridable Property HrmEmployeeHealths() As DbSet(Of HrmEmployeeHealth)
    Public Overridable Property HrmEmployeementHistories() As DbSet(Of HrmEmployeementHistory)
    Public Overridable Property HrmEmployeeRefrences() As DbSet(Of HrmEmployeeRefrence)
    Public Overridable Property HrmEmployeeRelations() As DbSet(Of HrmEmployeeRelation)
    Public Overridable Property HrmEmployees() As DbSet(Of HrmEmployee)
    Public Overridable Property HrmInternalRequisitions() As DbSet(Of HrmInternalRequisition)
    Public Overridable Property HrmInterviewDetails() As DbSet(Of HrmInterviewDetail)
    Public Overridable Property HrmInterviews() As DbSet(Of HrmInterview)
    Public Overridable Property HrmJobPosts() As DbSet(Of HrmJobPost)
    Public Overridable Property HrmJobTypes() As DbSet(Of HrmJobType)
    Public Overridable Property HrmSkills() As DbSet(Of HrmSkill)
    Public Overridable Property InterviewAssessments() As DbSet(Of InterviewAssessment)
    Public Overridable Property JobRequisitions() As DbSet(Of JobRequisition)
    Public Overridable Property Jobs() As DbSet(Of Job)
    Public Overridable Property KeyObjectives() As DbSet(Of KeyObjective)
    Public Overridable Property KeyResults() As DbSet(Of KeyResult)
    Public Overridable Property LeavePolicies() As DbSet(Of LeavePolicy)
    Public Overridable Property LeaveRequests() As DbSet(Of LeaveRequest)
    Public Overridable Property LoanSanctions() As DbSet(Of LoanSanction)
    Public Overridable Property LoanTypes() As DbSet(Of LoanType)
    Public Overridable Property OfferLetters() As DbSet(Of OfferLetter)
    Public Overridable Property Organizations() As DbSet(Of Organization)
    Public Overridable Property OverTimeSetups() As DbSet(Of OverTimeSetup)
    Public Overridable Property PayRollCutOffs() As DbSet(Of PayRollCutOff)
    Public Overridable Property Regions() As DbSet(Of Region)
    Public Overridable Property SalarySetups() As DbSet(Of SalarySetup)
    Public Overridable Property ShiftMasters() As DbSet(Of ShiftMaster)
    Public Overridable Property SpecialAllowances() As DbSet(Of SpecialAllowance)
    Public Overridable Property States() As DbSet(Of State)
    Public Overridable Property Terminations() As DbSet(Of Termination)
    Public Overridable Property TradeLicenses() As DbSet(Of TradeLicens)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property UserTypes() As DbSet(Of UserType)
    Public Overridable Property Allowances() As DbSet(Of Allowance)
    Public Overridable Property AllowancesDeductions() As DbSet(Of AllowancesDeduction)
    Public Overridable Property AllowanceTypes() As DbSet(Of AllowanceType)
    Public Overridable Property HrmAttendances() As DbSet(Of HrmAttendance)
    Public Overridable Property LeaveTypes() As DbSet(Of LeaveType)
    Public Overridable Property PublicHolidays() As DbSet(Of PublicHoliday)
    Public Overridable Property tbl_EmployeeAttendanceCalculations() As DbSet(Of tbl_EmployeeAttendanceCalculations)

End Class
