'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OfferLetter
    Public Property PK_OfferLetterId As Integer
    Public Property EmployeeId As String
    Public Property DesignationId As String
    Public Property DepartmentId As String
    Public Property JoiningDate As Nullable(Of Date)
    Public Property Salary As String

End Class
