'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Organization
    Public Property Id As Integer
    Public Property GroupOfCompaniesID As Nullable(Of Integer)
    Public Property Name As String
    Public Property ShortCode As String
    Public Property Email As String
    Public Property Address As String
    Public Property BaseCurrency As String
    Public Property CreatedBy As String
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As String
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
