'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_EmployeeAttendanceCalculations
    Public Property Id As Integer
    Public Property EmployeeId As Nullable(Of Integer)
    Public Property Name As String
    Public Property Department As String
    Public Property PresentDays As Nullable(Of Integer)
    Public Property LeaveDays As Nullable(Of Integer)
    Public Property AbsentDays As Nullable(Of Integer)
    Public Property TotalHoursWorked As String
    Public Property NormalOTHours As Nullable(Of Integer)
    Public Property WeekendOTHours As Nullable(Of Integer)
    Public Property PublicHolidaysOTHours As Nullable(Of Integer)

End Class
