'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Termination
    Public Property TerminatinId As Long
    Public Property EmployeeId As Nullable(Of Long)
    Public Property DesignationId As Nullable(Of Long)
    Public Property DepartmentId As Nullable(Of Long)
    Public Property ToDepartmentId As Nullable(Of Long)
    Public Property Type As Nullable(Of Integer)
    Public Property LastWorkingDate As Nullable(Of Date)
    Public Property [Date] As Nullable(Of Date)
    Public Property TerminationBy As Nullable(Of Long)
    Public Property Reason As String
    Public Property Active As Nullable(Of Boolean)
    Public Property CreatedBy As Nullable(Of Long)
    Public Property CreatedOn As Nullable(Of Date)
    Public Property LastModifiedBy As Nullable(Of Long)
    Public Property LastModifiedOn As Nullable(Of Date)
    Public Property IsDeleted As Nullable(Of Boolean)

End Class
